
title: ""
description: "An open, inclusive network embedded in the Digital Interactions Lab (DILab) at the Informatics Institute (IvI), University of Amsterdam."
qfin_logo: "/assets/images/qfin-logo-hero.png"
baseurl: ""  # If using a project site, set this to "/<repo>"
url: "https://yourusername.github.io"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

qfin_logo: "/assets/images/qfin-logo.jpg"
dilab_logo: "/assets/images/dilab-logo.svg"

markdown: kramdown
kramdown:
  input: GFM
